name: Build Hugo Site

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build the site
      run: hugo -d docs